---
# install mysql and configure root password
- apt: pkg=python-mysqldb
- mysql_user: name=root password=$db_root_pass
  ignore_errors: True
- mysql_user: |
    name=root password=$db_root_pass
    login_user=root login_password=$db_root_pass
- copy: src=dbs/my.cnf dest=/etc/mysql/my.cnf
- service: name=mysql state=restarted
