---
- name: gather installed containers
  action: shell lxc-list
  register: lxc_list
# create a machine
# takes $name
- name: get $name status
  action: shell lxc-info -s --name $name
  register: ${name}_status
- name: create a machine (only if does not exist)
  action: command lxc-create -t ubuntu -n $name
  only_if: "'$name' not in '''${lxc_list.stdout}'''"
- name: start $name
  action: command lxc-start -d --name $name
  only_if: "'${${name}_status}' !=  'state:   RUNNING'"
